### ISSUE TITLE
Cannot use SshKeyGenerator method without explicit usage

### ISSUE THREAD

**Issue by cancmrt** [ShawInnes/SshKeyGenerator#4]
Hi,
`var keygen = new SshKeyGenerator(2048);`

I get the nuget package but when i try to use something like in Examples code, this will give you the error
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0118	'SshKeyGenerator' is a namespace but is used like a type	
`
I solved this using expilicit version

`var keygen = new SshKeyGenerator.SshKeyGenerator(2048);`

but i think this need to solve.

**Comment by ShawInnes** [comment]
Oh yes, sorry about that.  The sample project was in the same namespace as the SshKeyGenerator class so it didn't require explicit namespacing.

I've updated the sample to make it clearer how to use it normally.  

I would prefer to fix the name of the class but that would be a breaking change so I'll just leave it as is, with better documentation/sample.
