### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by joerage** [ShawInnes/SshKeyGenerator#5]
Because the `RSACryptoServiceProvider` object is never disposed, program using this library will suffer from memory leak. This can easily be seen using this small sample program and watching its memory grow.

```
while (true)
{
  var keygen = new SshKeyGenerator.SshKeyGenerator(2048);
  var publicSshKey = keygen.ToRfcPublicKey();
}
```

_Note that `RSACryptoServiceProvider` contains unmanaged resources._

**Comment by ShawInnes** [comment]
Nice catch.  Thanks for the PR
