### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by shabakett** [ShawInnes/SshKeyGenerator#9]
Could you please change the license from CC-BY-4.0 to Apache or MIT?

**Comment by ShawInnes** [comment]
Sure, I think MIT would be best.  Could you explain why you'd like it changed though?  In hindsight, CC is probably not as appropriate for software as it would be for content, is that correct?

**Comment by shabakett** [comment]
Yes it is correct especially for commercial projects where developers do not like to share their code source.
